import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { AppSidebar } from "../user-page/navigation/sidebar";

export const metadata: Metadata = {
  title: "SDO-RTMS Track Document",
  description: "Generated by create next app",
};

export default function TrackDocumentLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <section className="min-h-screen w-full h-screen flex flex-col justify-center items-center">
          {children}
        </section>
      </SidebarInset>
    </SidebarProvider>
  );
}
