import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "DocuTrack Registration",
  description: "Generated by create next app",
};

export default function RegistrationLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="min-h-screen bg-[#77B254] flex flex-col items-center justify-center p-4">
      {children}
    </section>
  );
}
