import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SDO-RTMS Registration",
  description: "Generated by create next app",
};

export default function RegistrationLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="w-full h-screen flex items-center">{children}</section>
  );
}
