import type { Metadata } from "next";
import LoginFooter from "./navigation/Footer";

export const metadata: Metadata = {
  title: "DocuTrack Login",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <section className="min-h-screen bg-[#FBF3B9] flex flex-col items-center justify-center p-4">
        {children}
      </section>
      <LoginFooter />
    </>
  );
}
