import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SDO-RTMS Login",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="min-h-screen bg-[#355F2E] flex flex-col items-center justify-center p-4">
      {children}
    </section>
  );
}
