import type { Metadata } from "next";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/records-page/navigation/sidebar";

export const metadata: Metadata = {
  title: "DocuTrack Records - Data Entry",
  description: "Generated by create next app",
};

export default function RecordsDataEntryPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <section className="min-h-screen w-full h-screen flex flex-col p-8 justify-center items-center">
          {children}
        </section>
      </SidebarInset>
    </SidebarProvider>
  );
}
