import type { Metadata } from "next";
import Navbar from "./navigation/Navbar";
import bg from "@/public/bg.jpg";
import { AspectRatio } from "@/components/ui/aspect-ratio";
import Image from "next/image";
import Footer from "./navigation/Footer";

export const metadata: Metadata = {
  title: "SDO-RTMS User Page",
  description: "Generated by create next app",
};

export default function UserPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col min-h-screen overflow-hidden">
      <Navbar />
      <section className="flex-1 flex flex-col items-center justify-center p-8 overflow-hidden">
        {children}
      </section>
      <Footer />
    </div>
  );
}
