import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SDO-RTMS User Page",
  description: "Generated by create next app",
};

export default function UserPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="min-h-screen w-full h-screen flex flex-col justify-center items-center">{children}</section>
  );
}
